version: '3.4'

networks:
  stokapinet:

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: MyDatabasePass1234
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"     # SQL Server port
    volumes:
      - sql_data:/var/opt/mssql
      - sql_backups:/var/opt/sqlserver/backups
    networks:
     - stokapinet
  stockapi:
    build:
      context: .
      dockerfile: StockAPI\Dockerfile
    ports:
     - "8004:80"
    depends_on:
     - sql_server
    environment:
     - ASPNETCORE_ENVIRONMENT=Testing
     - PARAM_VAR=DockerStockDbConnectionTesting
    networks:
     - stokapinet
volumes:
    sql_data:
    sql_backups: